branch-defaults:
  master:
    environment: Cloudesgiback-env
environment-defaults:
  Cloudesgiback-env:
    branch: null
    repository: null
global:
  application_name: cloud_esgi_back
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
deploy:
  artifact: dist.zip
