export * from './user.model'
export * from './cours.model'
export * from './file.model'
export * from './chat.model'
export * from './message.model'
export * from './slot.model'
export * from './comment.model'